### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by FerDR89** [facuariasla/des6-2#1]
Buenas! ¿Cómo va eso?.

Estuve revisando la app y te dejo algunas cosas por corregir

- No esta la doc de Postman en el README y es un requisito para aprobar el desafío.
- El ID para compartir debería ser el número de sala u otro id identificatorio un poco más corto y fácil de compartir
![image](https://user-images.githubusercontent.com/74626765/161292448-3032f35d-1b34-451b-86bf-ce649b8d43ae.png)

Lo demás, esta excelente. 
Me encanto la ui, la jugabilidad y todos los detalles que le sumaste para personalizarlo (el de la tortuga esta genial)

**Comment by facuariasla** [comment]
Aa joya, apenas puedo arreglo eso, gracias por la devolución Fer!
