### ISSUE TITLE
Review #2 

### ISSUE THREAD

**Issue by FacundoEG** [facuariasla/des6-2#2]
Hola Facu ! como andas? mira te cuento que estoy probando la webapp, te quiero dejar unas cositas que note:

1. Fijate que cuando los dos jugadores se conectan, no te toma el nombre del contrincante y te lo deja como "logout"
![image](https://user-images.githubusercontent.com/79592789/161390769-8e6e43e8-6ef1-4c40-b87a-46f6115c8bf4.png)

2. Lo que si note que puede romper algo, es que cuando ya hay dos usuarios conectados a una sala se permite que entren mas (en este screen logre meter 2 usuarios mas) y genera que se todo pierda coordinación, así que te sugeriría que cambies eso para que cuando ya haya dos usuarios en una sala no se permitan entrar mas:
![image](https://user-images.githubusercontent.com/79592789/161390924-359a5359-4685-4385-9819-ca639cb0b691.png)

Por lo demas lo veo perfecto al desafío, muy cuidada la UI y genial que tengan password los users, eso suma puntos.

Si queres resolvete lo del punto 2 y volve a enviar tu desafío, pero en lineas generales ya con arreglar eso tenes todo aprobado!

Te mando un saludo y esperamos la devolución!

**Comment by facuariasla** [comment]
Hola Facu! si en cuanto a lo primero lo diseñe así de entrada y quedo, aunque el tagname oponente que recién se renderiza en la parte de /game, podría haber sido antes en las instrucciones, es verdad.

Y en cuanto al filtro a la hora de entrar a la sala, excelente, porque no me di cuenta ni se me ocurrió entrar con 3 cuentas jaja. Ahora teóricamente esta arreglado, mil gracias! cualquier cosa que haya pasado por alto dejo abierto el issue

**Comment by FacundoEG** [comment]
Hola Facu! genial por ese feature, ahi lo revise al desafío y quedo de 10 definitivamente! así que te felicito y te deseo lo mejor para el mod 7!

Saludos!
